name: deploy-naval
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: "Pull, rebuild and redeploy"
        run: |
          cd /home/pgeorgakopoulos/naval-deployment/naval
          git pull
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
      - name: "Reload nginx"
        run: |
          cd /home/pgeorgakopoulos/armada
          docker compose exec nginx nginx -s reload
